# Generated by crates/cantus_cpu/src/config.rs.
# Do not edit this file directly.

{ lib }: {
  monitor = lib.mkOption {
    type = lib.types.nullOr (lib.types.str);
    default = builtins.fromJSON "null";
    description = "The monitor to display on.";
  };
  layer = lib.mkOption {
    type = lib.types.enum [
      "background"
      "bottom"
      "top"
      "overlay"
    ];
    default = builtins.fromJSON "\"top\"";
    description = "The layer the app should be on.";
  };
  layer_anchor = lib.mkOption {
    type = lib.types.enum [
      "top"
      "bottom"
    ];
    default = builtins.fromJSON "\"top\"";
    description = "The corner/edge the application should anchor to.";
  };
  height = lib.mkOption {
    type = lib.types.number;
    default = builtins.fromJSON "50.0";
    description = "The height of the bar in logical pixels.";
  };
  spotify_client_id = lib.mkOption {
    type = lib.types.nullOr (lib.types.str);
    default = builtins.fromJSON "null";
    description = "Spotify client ID to use for authentication.";
  };
  timeline_future_minutes = lib.mkOption {
    type = lib.types.number;
    default = builtins.fromJSON "12.0";
    description = "How many minutes in the future to display in the timeline.";
  };
  timeline_past_minutes = lib.mkOption {
    type = lib.types.number;
    default = builtins.fromJSON "1.5";
    description = "How many minutes before the current time to display in the timeline.";
  };
  history_width = lib.mkOption {
    type = lib.types.number;
    default = builtins.fromJSON "100.0";
    description = "The width in logical pixels on the left where previous tracks are displayed.";
  };
  playlists = lib.mkOption {
    type = lib.types.addCheck (lib.types.listOf (lib.types.str)) (xs: builtins.length xs <= 8);
    default = builtins.fromJSON "[]";
    description = "Favourite playlists to display as buttons.";
  };
  ratings_enabled = lib.mkOption {
    type = lib.types.bool;
    default = builtins.fromJSON "false";
    description = "Whether star ratings should be enabled.";
  };
  weather_enabled = lib.mkOption {
    type = lib.types.bool;
    default = builtins.fromJSON "true";
    description = "Whether to show the weather and calendar module.";
  };
  location = lib.mkOption {
    type = lib.types.addCheck (lib.types.listOf (lib.types.number)) (xs: builtins.length xs == 2);
    default = builtins.fromJSON "[51.50740051269531,-0.12780000269412994]";
    description = "Latitude and longitude used for the weather pill.";
  };
  status_enabled = lib.mkOption {
    type = lib.types.bool;
    default = builtins.fromJSON "true";
    description = "Whether to show the system status module.";
  };
}
