#[allow(dead_code)]
mod config;

use serde_json::Value;
use std::{fmt::Write as _, fs};

const OUTPUT: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../generated-options.nix");
const HEADER: &str = "# Generated by `just options` from crates/cantus_cpu/src/config.rs.\n# Do not edit this file directly.\n\n{ lib }: {\n";

fn main() {
    let schema = schemars::schema_for!(config::Config);
    let schema = schema.as_value();
    let properties = schema["properties"].as_object().unwrap();
    let options = properties
        .iter()
        .fold(String::new(), |mut options, (name, property)| {
            writeln!(
                options,
                "{name}=lib.mkOption{{type={};default={};description={};}};",
                nix_type(property, schema),
                nix_value(&property["default"]),
                nix_string(property["description"].as_str().unwrap()),
            )
            .unwrap();
            options
        });
    let output = format!("{HEADER}{options}}}\n");

    fs::write(OUTPUT, output).unwrap();
}

fn nix_type(schema: &Value, root: &Value) -> String {
    if let Some(reference) = schema["$ref"].as_str() {
        return nix_type(&root["$defs"][reference.rsplit('/').next().unwrap()], root);
    }
    if let Some(values) = schema["enum"].as_array() {
        return format!(
            "lib.types.enum[{}]",
            join(values, |value| nix_string(value.as_str().unwrap()))
        );
    }
    if let Some(kinds) = schema["type"].as_array() {
        assert!(kinds.iter().any(|kind| kind == "string"));
        return "lib.types.nullOr (lib.types.str)".into();
    }

    match schema["type"].as_str().unwrap() {
        "string" => "lib.types.str".into(),
        "number" => "lib.types.number".into(),
        "boolean" => "lib.types.bool".into(),
        "array" => {
            let list = format!("lib.types.listOf ({})", nix_type(&schema["items"], root));
            let max = schema["maxItems"].as_u64().unwrap();
            let op = if schema["minItems"] == schema["maxItems"] {
                "=="
            } else {
                "<="
            };
            format!("lib.types.addCheck ({list}) (xs: builtins.length xs {op} {max})")
        }
        kind => panic!("unsupported config type: {kind}"),
    }
}

fn nix_value(value: &Value) -> String {
    match value {
        Value::Null => "null".into(),
        Value::Bool(value) => value.to_string(),
        Value::String(value) => nix_string(value),
        Value::Number(value) => {
            let value = (value.as_f64().unwrap() as f32).to_string();
            if value.starts_with('-') {
                format!("({value})")
            } else {
                value
            }
        }
        Value::Array(values) => format!("[{}]", join(values, nix_value)),
        Value::Object(_) => panic!("object defaults are not supported"),
    }
}

fn join(values: &[Value], f: impl Fn(&Value) -> String) -> String {
    values.iter().map(f).collect::<Vec<_>>().join(" ")
}

fn nix_string(value: &str) -> String {
    serde_json::to_string(value).unwrap().replace("${", "\\${")
}
